[package]
name = "osrsim"
version = "0.1.0"
authors = ["Nikolai Magnussen <nikolai@magnussen.tf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
